config/routes.rb
Rails.application.routes.draw do
	get 'articles/new', :to => 'my_articles#my_new'
	post 'articles12233444', :to => 'my_articles#my_create', as: :hello 
	get 'article/:asheesh', :to => 'my_articles#my_show', as: :bye 
	get 'articles', :to => 'my_articles#my_index', as: :articles
	get 'articles/:ankur/edit', :to => 'my_articles#my_edit', as: :edit
	put 'articles/:id', :to => 'my_articles#my_update', as: :update
	delete 'articles/:asheesh', :to => 'my_articles#my_destroy', as: :delete

	post '/articles/:article_id/comments', :to => 'my_comments#my_create', as: :hii 
	get 'articles/:article_id/comments/:id/edit', :to => 'my_comments#my_edit', as: :comment_edit
	put 'articles/:article_id/comments/:id', :to => 'my_comments#my_update', as: :comment_update

	delete 'articles/:article_id/comments/:id', :to => 'my_comments#my_destroy', as: :ruin

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments,  dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_articles_controller.rb
class MyArticlesController < ApplicationController
	
	def my_index
		@articles = Article.all
		
	end

	def my_new
		@article = Article.new
	end



	def my_create

	  # render plain: params[:article].inspect
	    # @article = Article.new(pooja_params)
	    @article = Article.new(title: params[:article][:title] , text: params[:article][:text])
		@article.save
		redirect_to bye_url(@article)  

	end

	def my_show
		@art = Article.find(params[:asheesh])

	end

	def my_edit
		@article = Article.find(params[:ankur])
		
	end

	def my_update
		@sonu = Article.find(params[:id])
		@sonu.update(title: params[:article][:title] , text: params[:article][:text])
		redirect_to bye_path(@sonu)
		
	end


	def my_destroy
	  @monu = Article.find(params[:asheesh])
	  @monu.destroy
	 
	  redirect_to articles_path
	end


end

app/controllers/my_comments_controller.rb
class MyCommentsController < ApplicationController

	def my_create
		byebug
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(commenter: params[:comment][:commenter], body: params[:comment][:body])
		redirect_to bye_path(@article)
	end


	def my_edit
		@art = Article.find(params[:article_id])
		@comment = @art.comments.find(params[:id])	
	end

	def my_update
		@art = Article.find(params[:article_id])
		@comment = @art.comments.find(params[:id])	
		@comment.update(commenter: params[:comment][:commenter], body: params[:comment][:body])
		redirect_to bye_path(@art)
		
	end


	def my_destroy
		@pooja = Article.find(params[:article_id])
		@comment = @pooja.comments.find(params[:id])
		@comment.destroy
		redirect_to bye_path(@pooja)
	end
 

  # private
  #   def comment_params
  #     params.require(:comment).permit(:commenter, :body)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_articles_helper.rb
module MyArticlesHelper
end

app/helpers/my_comments_helper.rb
module MyCommentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiffrentModelController</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_articles/_form.html.erb
<h1>heloo pooja!!!!</h1>
 

<%= form_for  @article, url: @article.new_record? ? hello_path : update_path(@article), local: true, method: @article.new_record? ? :post : :put do |form| %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit%>
  </p>
<% end %>

app/views/my_articles/my_edit.html.erb
<h1>heloo Asheesh!!!!</h1>
 
<%= render "form" %>

app/views/my_articles/my_index.html.erb
<h1>Listing Articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @articles.each do |shruti| %>
    <tr>
      <td><%= shruti.title %></td>
      <td><%= shruti.text %></td>
      <td><%= link_to 'Show', bye_path(shruti) %></td>
      <td><%= link_to 'Edit', edit_path(shruti) %></td>
      <td><%= link_to 'Destroy', delete_path(shruti),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/my_articles/my_new.html.erb
<h1>heloo pooja!!!!</h1>
 
<%= render "form" %>

app/views/my_articles/my_show.html.erb
<strong>title</strong><br>
<%= @art.title %><br>
<strong>text</strong><br>
<%= @art.text %>


 <h2>Comments</h2>
 <% @art.comments.each do |comment| %>

<%= render 'my_comments/comment', comment: comment %>
<%end%>
 
<h2>Add a comment:</h2>
<%= render 'my_comments/form' %>



<%= link_to "index", articles_path %>

app/views/my_comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<%= link_to 'Edit', comment_edit_path(@art, comment) %>

<p>
  <%= link_to 'Destroy Comment', ruin_path(@art, comment),
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/my_comments/_form.html.erb
<%byebug%>
<%= form_for :comment, url: @comment.present? ? comment_update_path : hii_path(@art), method: @comment.present? ? :put : :post do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/my_comments/my_edit.html.erb
<%= render "form" %>